version: '3'
services:
  admin:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: admin
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      - postgres
    networks:
      - app_network

  customers:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: customers
    env_file:
      - .env
    ports:
      - 3001:3001
    depends_on:
      - postgres
    networks:
      - app_network

  postgres:
    image: postgres:alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=johndoe
      - POSTGRES_PASSWORD=randompassword
      - POSTGRES_DB=postgres
    ports:
      - '5433:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
    driver: bridge
