version: '3'
services:
  admin:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - APP_NAME=admin
    ports:
      - ${ADMIN_PORT}:${ADMIN_PORT}
    depends_on:
      - db
    networks:
      - app_network

  customers:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - APP_NAME=customers
    env_file:
      - .env
    ports:
      - ${CUSTOMERS_PORT}:${CUSTOMERS_PORT}
    depends_on:
      - db
    networks:
      - app_network

  db:
    image: postgres:alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=johndoe
      - POSTGRES_PASSWORD=randompassword
      - POSTGRES_DB=postgres
    ports:
      - 5433:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
    driver: bridge
